### ISSUE TITLE
'unsafe-eval' is not needed

### ISSUE THREAD

**Issue by foooomio** [ArcCosine/fake-google-keyboard-shortcuts#2]
https://github.com/ArcCosine/fake-google-keyboard-shortcuts/blob/801a63bf237569c198c6b43b8b4e4705a879da7e/manifest.json#L6

cf. https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval

**Comment by ArcCosine** [comment]
I erase it somewhere
