### ISSUE TITLE
chrome.extension doesn't have 'connect' method

### ISSUE THREAD

**Issue by foooomio** [ArcCosine/fake-google-keyboard-shortcuts#3]
https://github.com/ArcCosine/fake-google-keyboard-shortcuts/blob/801a63bf237569c198c6b43b8b4e4705a879da7e/content.js#L2

Use `chrome.runtime.connect`, and please consider using simple one-time requests instead of long-lived connections.
cf. https://developer.chrome.com/extensions/messaging#simple

**Comment by ArcCosine** [comment]
The next version will adopt the recommended method.Thank you.
