### ISSUE TITLE
KeyboardEvent.keyCode is deprecated

### ISSUE THREAD

**Issue by foooomio** [ArcCosine/fake-google-keyboard-shortcuts#4]
https://github.com/ArcCosine/fake-google-keyboard-shortcuts/blob/801a63bf237569c198c6b43b8b4e4705a879da7e/content.js#L71

Use KeyboardEvent.key instead.
https://developer.mozilla.org/ja/docs/Web/API/KeyboardEvent/keyCode
https://developer.mozilla.org/ja/docs/Web/API/KeyboardEvent/key

**Comment by ArcCosine** [comment]
Next version use "key".
