### ISSUE TITLE
How to behave on opening the page

### ISSUE THREAD

**Issue by foooomio** [ArcCosine/fake-google-keyboard-shortcuts#5]
Without ctrl key, this exteinsion opens the page in the same window even if opning new window is on by Google's settings. I suggest that removing the target attribute should be removed.

https://github.com/ArcCosine/fake-google-keyboard-shortcuts/blob/801a63bf237569c198c6b43b8b4e4705a879da7e/content.js#L40-L44

**Comment by ArcCosine** [comment]
If you do the same thing on the same page, you will not be able to exclude this code because it will be set to open a new tab.
In the first place, I have to put target = "_ blank" :)
I will implement this countermeasure somewhere.
